language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
before_script:
  - npm install -g gulp
script:
  - npm run lint
  - npm test
  - gulp
notifications:
  slack: fedshq:CmawQ9tM6y8blGnkc7nC1IuT